### ISSUE TITLE
Astronomy phaseofMoon

### ISSUE THREAD

**Issue by dajanamilk** [dknoodle/WUnderground.Net#9]
Hi, Thanks for this helpful project, is it possible to add the phaseofMoon to the AstronomyResponse ?  Also If possible the hemisphere. Bellow I added the json response to make it easier.

`

{
	"response": {
		"version": "0.1",
		"termsofService": "http://www.wunderground.com/weather/api/d/terms.html",
		"features": {
			"astronomy": 1
		}
	},
	"moon_phase": {
		"percentIlluminated": "2",
		"ageOfMoon": "28",
		"phaseofMoon": "Waning Crescent",
		"hemisphere": "South",
		"current_time": {
			"hour": "11",
			"minute": "48"
		},
		"sunrise": {
			"hour": "6",
			"minute": "37"
		},
		"sunset": {
			"hour": "17",
			"minute": "37"
		},
		"moonrise": {
			"hour": "5",
			"minute": "05"
		},
		"moonset": {
			"hour": "16",
			"minute": "53"
		}
	},
	"sun_phase": {
		"sunrise": {
			"hour": "6",
			"minute": "37"
		},
		"sunset": {
			"hour": "17",
			"minute": "37"
		}
	}
}
`

**Comment by dknoodle** [comment]
@Mnemonic7 - This was actually fixed in the latest NuGet package update last Wednesday.

WUnderground likes to randomly return properties with underscore characters like "moon_phase".  I did just notice your sample JSON data includes a "sun_phase" section which is not currently implemented.  What their documentation lists and what their API returns has a lot of inconsistencies.

I published an update to add the SunPhase as well.  The new 2.0.5 package has been uploaded to NuGet and should be available soon.
